Repository mineadmin/components, pull requests merged in 2024-06, with the labels that each got.

#89 Update InstallProjectCommand.php
  src/mine-core/src/Command/InstallProjectCommand.php
Labels: bug, size:XS, MineCore

#90 Remove auto cs-fix author
  .github/workflows/code-coverage.yml
  .github/workflows/pull-request-cs-fixer.yml
  .github/workflows/test.yml
Labels: size:S

#91 Add PluginNotFoundException and make Plugin::read more safe
  src/AppStore/src/Exception/PluginNotFoundException.php
  src/AppStore/src/Plugin.php
Labels: enhancement, size:M, lgtm

#92 Optimize Command Component in App Store
  src/AppStore/src/Command/AbstractCommand.php
  src/AppStore/src/Command/CreateCommand.php
  src/AppStore/src/Command/DownloadCommand.php
  src/AppStore/src/Command/InitialCommand.php
  src/AppStore/src/Command/InstallCommand.php
  src/AppStore/src/Command/ListCommand.php
  src/AppStore/src/Command/LocalListCommand.php
  src/AppStore/src/Command/ScriptCommand.php
  src/AppStore/src/Command/UninstallCommand.php
Labels: enhancement, size:L, lgtm

#94 Remove env space between k-v
  src/mine-core/src/Command/InstallProjectCommand.php
Labels: size:XS, lgtm, MineCore

#95 Added composer.json normalize support
  .github/workflows/pull-request-cs-fixer.yml
  .github/workflows/test.yml
  composer.json
  src/AppStore/composer.json
  src/AppStore/src/Command/CreateCommand.php
  src/AppStore/src/Command/InitialCommand.php
  src/Crontab/composer.json
  src/HttpServer/composer.json
  src/Module/composer.json
  src/Module/src/Command/Creater/CreateModel.php
  src/SecurityAccess/composer.json
  src/SecurityBundle/composer.json
  src/SecurityBundle/src/AbstractUserProvider.php
  src/SecurityHttp/composer.json
  src/SecurityHttp/tests/Cases/UserProviderTest.php
  src/Support/composer.json
  src/jwt-auth/composer.json
  src/mine-core/composer.json
  src/mine-core/src/Command/Creater/CreateModel.php
  src/mine-generator/composer.json
  src/mine-generator/publish/generator.php
  src/mine-generator/src/ControllerGenerator.php
  src/mine-generator/src/DtoGenerator.php
  src/mine-generator/src/MapperGenerator.php
  src/mine-generator/src/ModelGenerator.php
  src/mine-generator/src/RequestGenerator.php
  src/mine-generator/src/ServiceGenerator.php
  src/mine-generator/src/VueIndexGenerator.php
  src/mine-helpers/composer.json
  src/mine-service/composer.json
  src/next-core-x/composer.json
  src/office/composer.json
  src/translatable/composer.json
Labels: enhancement, size:L, SecurityHttp, UnitTest, Support, Composer, MineGenerator, Crontab, Office, MineCore, SecurityBundle, NextCoreX, JwtAuth, MineHelpers, Module, HttpServer, SecurityAccess, Translatable

#93 Update some statments
  src/Module/src/Command/Creater/CreateFormRequest.php
  src/Module/src/Command/Creater/CreateModel.php
  src/Module/src/Command/Migrate/MineMigrate.php
  src/Module/src/Command/Migrate/MineMigrateRollback.php
  src/Module/src/Command/Migrate/MineMigrateRun.php
  src/Module/src/Command/Seeder/MineSeeder.php
  src/Module/src/Command/Seeder/MineSeederRun.php
  src/jwt-auth/src/JWT.php
  src/mine-generator/src/CodeGenerator.php
  src/mine-generator/src/MineGenerator.php
  src/mine-generator/src/ModuleGenerator.php
  src/mine-helpers/src/AppVerify.php
  src/mine-helpers/src/ConsoleTable.php
  src/mine-helpers/src/Id.php
  src/mine-helpers/src/LoginUser.php
  src/mine-helpers/src/Str.php
  src/mine-service/src/Abstracts/BaseDao.php
Labels: enhancement, size:L, lgtm, MineGenerator, JwtAuth, MineHelpers, Module

#97 Remove mine.json validation
  src/AppStore/src/Plugin.php
Labels: enhancement, size:XS

#99 Optimal method `Plugin::install`
  src/AppStore/src/Plugin.php
Labels: size:S

#100 Update Plugin
  src/AppStore/src/Plugin.php
Labels: size:M

#98 Fix path differences given func `checkPlugin`
  src/AppStore/src/Plugin.php
Labels: bug, size:XS, lgtm

#102 fixed
  .github/workflows/release.yml
  src/AppStore/.github/workflows/close-pull-request.yml
  src/AppStore/.github/workflows/release.yml
  src/Crontab/.github/workflows/close-pull-request.yml
  src/Crontab/.github/workflows/release.yml
  src/HttpServer/.github/workflows/close-pull-request.yml
  src/HttpServer/.github/workflows/release.yml
  src/jwt-auth/.github/workflows/close-pull-request.yml
  src/jwt-auth/.github/workflows/release.yml
  src/mine-core/.github/workflows/close-pull-request.yml
  src/mine-core/.github/workflows/release.yml
  src/mine-generator/.github/workflows/close-pull-request.yml
  src/mine-generator/.github/workflows/release.yml
  src/mine-helpers/.github/workflows/close-pull-request.yml
  src/mine-helpers/.github/workflows/release.yml
  src/mine-service/.github/workflows/close-pull-request.yml
  src/mine-service/.github/workflows/release.yml
  src/office/.github/workflows/close-pull-request.yml
  src/office/.github/workflows/release.yml
  src/translatable/.github/workflows/close-pull-request.yml
  src/translatable/.github/workflows/release.yml
Labels: size:M, MineGenerator, Crontab, Office, MineCore, JwtAuth, MineHelpers, HttpServer, Translatable

#103 fix: filterExecuteAttributes 地址引用导致aop后变量指针错误的问题
  src/mine-core/src/Traits/MapperTrait.php
Labels: bug, size:S, MineCore

#104 Removing cygwin code
  src/mine-core/src/MineStart.php
Labels: size:XS, MineCore

#105 fix(config-provider): ensure class_exists before instantiation
  src/AppStore/src/ConfigProvider.php
Labels: bug, size:XS, lgtm
