Repository mineadmin/components, pull requests merged in 2024-12, with the labels that each got.

#135 Enhanced validation checks for refresh tokens to ensure they meet specified constraints.
  src/Jwt/AbstractJwt.php
  src/Jwt/AccessTokenConstraint.php
Labels: enhancement, size:M

#139 Optimize plugin namespace
  src/AppStore/src/Command/CreateCommand.php
Labels: enhancement, size:XS, lgtm

#140 added(JwtAuth): 添加用户 和当前用户 Interface
  src/JwtAuth/Interfaces/CurrentUserInterface.php
  src/JwtAuth/Interfaces/UserInterface.php
Labels: enhancement, size:M, lgtm
