Repository mineadmin/components, pull requests merged in 2024-07, with the labels that each got.

#106 Revert "fix: filterExecuteAttributes 地址引用导致aop后变量指针错误的问题"
  src/mine-core/src/Traits/MapperTrait.php
Labels: bug, size:S, MineCore

#107 feat(controller-generator): add dynamic primary key retrieval
  src/mine-generator/src/ControllerGenerator.php
Labels: enhancement, size:S, lgtm, MineGenerator

#110 fix(jwt-auth): use public key for token validation (#104)
  src/jwt-auth/src/JWT.php
Labels: bug, size:XS, lgtm, JwtAuth

#111 fix: run plugin script command fail
  src/AppStore/src/Plugin.php
Labels: bug, size:S, lgtm

#112 [Improvement] Enhance the plugin installation workflow
  src/AppStore/src/Plugin.php
Labels: enhancement, size:XS

#114 chore: [#Resubmit] 注解去掉try
  src/mine-core/src/Aspect/ResubmitAspect.php
Labels: size:M, MineCore

#115 Introduce Packaging and Version Distribution Commands for Plugins
  src/AppStore/bin/release.sh
  src/AppStore/bin/split-linux.sh
  src/AppStore/bin/splitsh-lite
  src/AppStore/bin/splitsh-lite-linux
  src/AppStore/src/Command/Repository/PushCommand.php
  src/AppStore/src/Command/Repository/ReleaseCommand.php
  src/AppStore/src/Plugin.php
  src/mine-core/src/Aspect/ResubmitAspect.php
Labels: enhancement, size:L, MineCore

#117 Remove Automatic Installation of App Store
  .php-cs-fixer.php
  src/mine-core/.php-cs-fixer.php
  src/mine-core/src/Command/InstallProjectCommand.php
  src/office/.php-cs-fixer.php
  src/translatable/.php-cs-fixer.php
  src/translatable/.travis.yml
Labels: size:XL, Office, MineCore, Translatable

#118 Optimize download logic
  src/AppStore/src/Service/Impl/AppStoreServiceImpl.php
Labels: size:XS

#119 chore: phpoffice 驱动添加callbackData回调
  src/office/src/Excel/PhpOffice.php
Labels: size:XS, Office

#120 refactor: change $localPluginPath path
  src/AppStore/src/Service/Impl/AppStoreServiceImpl.php
Labels: size:XS
