Repository mineadmin/components, pull requests merged in 2025-07, with the labels that each got.

#151 feat(crontab): add database-based crontab configuration and execution
  composer.json
  src/Crontab/.gitattributes
  src/Crontab/.github/workflows/close-pull-request.yml
  src/Crontab/.github/workflows/release.yml
  src/Crontab/Database/Migrations/2024_03_26_020159_create_crontab.php
  src/Crontab/Database/Migrations/2024_03_26_020825_create_crontab_execute_log.php
  src/Crontab/LICENSE
  src/Crontab/README.md
  src/Crontab/composer.json
  src/Crontab/src/Aspect/CrontabExecutorAspect.php
  src/Crontab/src/Command/CrontabMigrateCommand.php
  src/Crontab/src/ConfigProvider.php
  src/Crontab/src/Crontab.php
  src/Crontab/src/CrontabContainer.php
  src/Crontab/src/CrontabUrl.php
  src/Crontab/src/Listener/CrontabProcessStarredListener.php
  src/Crontab/src/Schedule.php
  tests/Crontab/Cases/Aspect/CrontabExecutorAspectTest.php
  tests/Crontab/Cases/ConfigProviderTest.php
  tests/Crontab/Cases/CrontabContainerTest.php
  tests/Crontab/Cases/CrontabTest.php
  tests/Crontab/Cases/CrontabUrlTest.php
  tests/Crontab/Cases/Listener/CrontabProcessStarredListenerTest.php
  tests/Crontab/Cases/ScheduleTest.php
Labels: enhancement, size:XXL, UnitTest, Composer, Crontab

#153 refactor(AbstractTokenMiddleware, Factory): simplify token handling and improve configuration retrieval
  src/Jwt/Factory.php
  src/JwtAuth/Annotation/Auth.php
  src/JwtAuth/Event/LogoutEvent.php
  src/JwtAuth/Event/UserLoginEvent.php
  src/JwtAuth/Interfaces/CheckTokenInterface.php
  src/JwtAuth/Interfaces/CurrentUserInterface.php
  src/JwtAuth/Interfaces/UserInterface.php
  src/JwtAuth/Middleware/AbstractTokenMiddleware.php
  tests/JwtAuth/AbstractTokenMiddlewareTest.php
Labels: enhancement, size:L

#154 fix(LocalListCommand): correct array merge syntax
  src/AppStore/src/Command/LocalListCommand.php
Labels: bug, size:XS, lgtm
