Repository mineadmin/components, pull requests merged in 2025-01, with the labels that each got.

#141 src/Upload/Listener/UploadListener.php:Fix 传完成主动删除/tmp临时文件
  src/Upload/Listener/UploadListener.php
Labels: bug, size:XS, lgtm

#143 feat(Jwt): add custom builder callback support
  bin/release.sh
  src/Jwt/AbstractJwt.php
  src/Jwt/JwtInterface.php
Labels: enhancement, size:S

#144 Fix crontab bug 0124
  src/mine-core/src/Listener/ResumeExitCoordinatorListener.php
Labels: bug, size:XS, lgtm, MineCore
